version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-browsers
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Paris"
      NODE_ENV: production
      CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm i
      - run:
          name: npm-install-dev-dependency
          command: npm i --only=dev
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test